name: nasa
description: A Flutter NASA application.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
