name: nasa
description: A Flutter NASA application.

publish_to: 'none'

version: 0.0.2+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/nasa_logo.png